

# Video presentation: https://www.youtube.com/watch?v=Dt0vx-7e_B0&t=1740s
bin/compile_time_logging: compile_time_logging.cpp bin
	g++ -o bin/compile_time_logging -O2 -Wall -std=c++20 compile_time_logging.cpp

# Video presentation: https://www.youtube.com/watch?v=BYpcAEfG3mo
bin/global_api_injection: global_api_injection.cpp bin
	g++ -o bin/global_api_injection -O2 -Wall -std=c++20 global_api_injection.cpp

bin:
	mkdir -p bin
